(() => {
  const TARGETS_KEY='parrotTargets',OUTBOX_KEY='parrotAmbiguityOutbox',OUTBOX_MAX=100,RECEIPT_TIMEOUT_MS=12000,RECEIPT_POLL_MS=250;
  const localFence=new Set(),runnerRegistry=ParrotRunnerRegistry.create(),sleep=(ms)=>new Promise(r=>setTimeout(r,ms));
  async function loadTargets(){const d=await chrome.storage.local.get(TARGETS_KEY);return Array.isArray(d[TARGETS_KEY])?d[TARGETS_KEY]:[];}async function getTarget(id){return(await loadTargets()).find(t=>t.id===id)||null;}async function patchTarget(id,patch){const ts=await loadTargets(),i=ts.findIndex(t=>t.id===id);if(i<0)return null;ts[i]={...ts[i],...patch};await chrome.storage.local.set({[TARGETS_KEY]:ts});return ts[i];}
  async function loadOutbox(){const d=await chrome.storage.local.get(OUTBOX_KEY);return Array.isArray(d[OUTBOX_KEY])?d[OUTBOX_KEY]:[];}async function saveOutbox(v){await chrome.storage.local.set({[OUTBOX_KEY]:v});}async function persistAmbiguity(receipt){const out=ParrotRouteState.putAmbiguityReceipt(await loadOutbox(),receipt,OUTBOX_MAX);await saveOutbox(out);localFence.add(receipt.queueId);return out;}async function ackAmbiguity(id){await saveOutbox(ParrotRouteState.ackAmbiguityReceipt(await loadOutbox(),id));}
  async function waitForStrongReceipt(before){const a=globalThis.ParrotSiteAdapter,deadline=Date.now()+RECEIPT_TIMEOUT_MS;while(Date.now()<deadline){const after=a.getUserMessageCount(),generating=a.isGenerating();if(ParrotRouteState.classifyStrongReceipt({beforeUserCount:before,afterUserCount:after,generating})==='delivered')return{delivered:true,afterUserCount:after,generationObserved:generating};await sleep(RECEIPT_POLL_MS);}return{delivered:false,afterUserCount:a.getUserMessageCount(),generationObserved:a.isGenerating()};}
  async function sendPrompt(text,detectCooldown=true){const a=globalThis.ParrotSiteAdapter;if(!a?.matches?.())return{ok:false,reason:'provider_mismatch'};const cd=detectCooldown?a.classifyCooldown?.():null;if(cd)return{ok:false,reason:'cooldown',cooldown:cd};if(a.isGenerating())return{ok:false,reason:'generating'};const before=a.getUserMessageCount();if(!text||!a.setComposerText(text))return{ok:false,reason:'composer_unavailable'};let b=null,deadline=Date.now()+1500;while(Date.now()<deadline){b=a.getSendButton();if(b&&!b.disabled&&b.getAttribute('aria-disabled')!=='true')break;await sleep(50);}if(!b||b.disabled||b.getAttribute('aria-disabled')==='true')return{ok:false,reason:'send_unavailable'};b.click();const e=await waitForStrongReceipt(before);return e.delivered?{ok:true,evidence:e}:{ok:false,reason:'strong_receipt_timeout',evidence:e,attempted:true};}
  async function composeTargetPrompt(t){return ParrotPromptCompose.compose(t,await loadTargets(),{firstSend:Number(t?.sentCount||0)===0});}async function stopIfRequired(t,now=Date.now()){const r=ParrotRepeatPolicy.stopReason(t,now);if(!r||r==='not_running')return r;await patchTarget(t.id,{status:'stopped',stopReason:r});return r;}
  async function applyCooldown(id,target,cd,now=Date.now()){const same=target.cooldownKind===cd.kind,attempt=same?Number(target.cooldownStep??target.cooldownAttempt??0):0,next=ParrotRepeatPolicy.nextCooldown(cd.kind,attempt,now);await patchTarget(id,{cooldownKind:next.kind,cooldownStep:next.attempt,cooldownAttempt:undefined,cooldownUntil:next.until,lastError:cd.code||cd.kind});return next;}async function clearCooldown(id){await patchTarget(id,{cooldownKind:'',cooldownStep:0,cooldownAttempt:undefined,cooldownUntil:null,lastError:''});}
  async function gateCooldown(id,target){if(target.cooldownEnabled===false){if(target.cooldownKind||target.cooldownUntil||target.cooldownAttempt)await clearCooldown(id);return false;}if(!ParrotRepeatPolicy.cooldownDue(target))return true;const cd=globalThis.ParrotSiteAdapter.classifyCooldown?.();if(!cd){if(Number(target.cooldownUntil||0)>0)await clearCooldown(id);return false;}await applyCooldown(id,target,cd);return true;}
  async function waitUntilIdleOrStopped(id){let saw=globalThis.ParrotSiteAdapter.isGenerating();while(true){const t=await getTarget(id);if(!t||t.status!=='running')return false;const g=globalThis.ParrotSiteAdapter.isGenerating();saw||=g;if(saw&&!g)return true;await sleep(500);}}async function handleSendFailure(id,target,result){if(result.reason==='generating')return 500;if(result.reason==='cooldown'){const n=await applyCooldown(id,target,result.cooldown);return Math.min(1000,n.minutes*60000);}await patchTarget(id,{lastError:result.reason||'send_failed'});return Math.max(1000,Number(target.delaySec||3)*1000);}
  const successPatch=(t)=>({sentCount:Number(t.sentCount||0)+1,lastSentAt:Date.now(),cooldownKind:'',cooldownStep:0,cooldownAttempt:undefined,cooldownUntil:null,lastError:''});
  async function runResponseMode(id,token,delay=0){try{if(delay>0)await sleep(delay);while(runnerRegistry.isCurrent(id,token)){const t=await getTarget(id);if(!t||t.status!=='running'||t.mode!=='response')break;if(await stopIfRequired(t))break;if(await gateCooldown(id,t)){await sleep(500);continue;}if(globalThis.ParrotSiteAdapter.isGenerating()){await sleep(500);continue;}const r=await sendPrompt(await composeTargetPrompt(t),t.cooldownEnabled!==false);if(!r.ok){await sleep(await handleSendFailure(id,t,r));continue;}await patchTarget(id,successPatch(t));if(!await waitUntilIdleOrStopped(id))break;const f=await getTarget(id);await sleep(Math.max(0,Number(f?.delaySec||0)*1000));}}finally{runnerRegistry.release(id,token);}}
  async function runIntervalMode(id,token,delay=0){try{if(delay>0)await sleep(delay);while(runnerRegistry.isCurrent(id,token)){const t=await getTarget(id);if(!t||t.status!=='running'||t.mode!=='interval')break;if(await stopIfRequired(t))break;if(await gateCooldown(id,t)){await sleep(500);continue;}if(!ParrotRepeatPolicy.intervalDue(t)||globalThis.ParrotSiteAdapter.isGenerating()){await sleep(500);continue;}const r=await sendPrompt(await composeTargetPrompt(t),t.cooldownEnabled!==false);if(!r.ok){await sleep(await handleSendFailure(id,t,r));continue;}await patchTarget(id,successPatch(t));await sleep(500);}}finally{runnerRegistry.release(id,token);}}
  function startRunner(id,mode,delay=0){return runnerRegistry.startIfIdle(id,mode,token=>(mode==='interval'?runIntervalMode:runResponseMode)(id,token,delay).catch(()=>{}));}
  function pruneInactiveRunners(targets){runnerRegistry.prune(targets);}
  async function armMatchingRunningTargets(targets){const list=Array.isArray(targets)?targets:await loadTargets();pruneInactiveRunners(list);for(const t of list){if(ParrotRunnerPolicy.shouldArm(t,location.href))startRunner(t.id,t.mode,ParrotRunnerPolicy.autoArmDelayMs(t));}return list;}
  function routePayload(r){return String(r?.payload??r?.prompt??r?.message??'');}
  async function deliverRoute(route){const q=String(route?.queueId||'');if(!q)return{ok:false,reason:'missing_queue_id'};if(localFence.has(q))return{ok:false,reason:'locally_fenced_ambiguous'};if(!ParrotRouteState.canAutoDispatch(route))return{ok:false,reason:'not_pending'};const before=globalThis.ParrotSiteAdapter.getUserMessageCount(),r=await sendPrompt(routePayload(route),true);if(r.ok){const receipt={queueId:q,deliveredAt:Date.now(),beforeUserCount:before,afterUserCount:r.evidence.afterUserCount,generationObserved:r.evidence.generationObserved};try{await chrome.runtime.sendMessage({type:'PARROT_ROUTE_DELIVERED',queueId:q,receipt});}catch{}return{ok:true,status:'delivered',receipt};}if(!r.attempted)return r;const receipt=ParrotRouteState.sanitizeAmbiguityReceipt({queueId:q,ambiguousAt:Date.now(),beforeUserCount:before,afterUserCount:r.evidence?.afterUserCount,generationObserved:r.evidence?.generationObserved,reason:'strong_receipt_timeout'});await persistAmbiguity(receipt);try{const ack=await chrome.runtime.sendMessage({type:'PARROT_ROUTE_AMBIGUOUS',receipt});if(ack?.ack===true)await ackAmbiguity(q);}catch{}return{ok:false,status:'ambiguous',reason:'strong_receipt_timeout',receipt};}
  async function flushAmbiguityOutbox(){for(const receipt of await loadOutbox()){localFence.add(receipt.queueId);try{const ack=await chrome.runtime.sendMessage({type:'PARROT_ROUTE_AMBIGUOUS',receipt});if(ack?.ack===true)await ackAmbiguity(receipt.queueId);}catch{}}}
  chrome.runtime.onMessage.addListener((m,_s,reply)=>{if(m?.type==='PARROT_START'){getTarget(m.targetId).then(t=>{if(!t||t.status!=='running')return reply({ok:false,reason:'target_not_running'});if(!['response','interval'].includes(t.mode))return reply({ok:false,reason:'unsupported_mode'});reply({ok:true,started:startRunner(m.targetId,t.mode,Math.max(0,Number(m.delayMs||0))),mode:t.mode});}).catch(e=>reply({ok:false,reason:String(e?.message||e)}));return true;}if(m?.type==='PARROT_ROUTE_DELIVER'){deliverRoute(m.route).then(reply).catch(e=>reply({ok:false,reason:'content_error',error:String(e?.message||e)}));return true;}return false;});
  chrome.storage.onChanged.addListener((c,a)=>{if(a!=='local'||!c[TARGETS_KEY])return;const n=Array.isArray(c[TARGETS_KEY].newValue)?c[TARGETS_KEY].newValue:[];armMatchingRunningTargets(n).catch(()=>{});});
  flushAmbiguityOutbox().then(()=>armMatchingRunningTargets()).catch(()=>{});
})();
