const TARGETS_KEY='parrotTargets',ROUTE_QUEUE_KEY='parrotRouteQueue',EVENTS_KEY='parrotEvents',COMPLETE_PREFIX='https://parrot.invalid/complete/',$=id=>document.getElementById(id),DM=ParrotDashboardModel;let workers=[],routes=[],page=0;init();
async function init(){$('refresh').addEventListener('click',refresh);$('newTarget').addEventListener('click',()=>chrome.runtime.openOptionsPage?.());$('searchWorkers').addEventListener('input',()=>{page=0;renderWorkers();});$('filterWorkers').addEventListener('change',()=>{page=0;renderWorkers();});$('workerPageSize').addEventListener('change',()=>{page=0;renderWorkers();});$('workerPrev').addEventListener('click',()=>{page=Math.max(0,page-1);renderWorkers();});$('workerNext').addEventListener('click',()=>{page+=1;renderWorkers();});$('workersBody').addEventListener('click',workerAction);$('routingBody').addEventListener('click',routeAction);await refresh();}
async function loadTargets(){const d=await chrome.storage.local.get(TARGETS_KEY);return Array.isArray(d[TARGETS_KEY])?d[TARGETS_KEY]:[];}async function saveTargets(targets){await chrome.storage.local.set({[TARGETS_KEY]:targets});}
async function refresh(){const data=await chrome.storage.local.get([TARGETS_KEY,ROUTE_QUEUE_KEY,EVENTS_KEY]);routes=Array.isArray(data[ROUTE_QUEUE_KEY])?data[ROUTE_QUEUE_KEY]:[];const targets=Array.isArray(data[TARGETS_KEY])?data[TARGETS_KEY]:[],tabs=await chrome.tabs.query({url:'https://chatgpt.com/*'});workers=targets.map(target=>{const tab=tabs.find(c=>normalizeUrl(c.url)===normalizeUrl(target.url)),structure=ParrotRouteState.classifyTabStructure(tab);return{target,tab,structure};});renderStats();renderWorkers();renderRoutes();renderEvents(data[EVENTS_KEY]);}
function normalizeUrl(raw){try{const u=new URL(raw);u.search='';u.hash='';return u.toString().replace(/\/$/,'');}catch{return String(raw||'').replace(/[?#].*$/,'').replace(/\/$/,'');}}
function renderStats(){$('statTargets').textContent=workers.length;$('statOpen').textContent=workers.filter(w=>w.tab).length;$('statRunning').textContent=workers.filter(w=>w.target.status==='running').length;$('statAttention').textContent=workers.filter(w=>DM.isAttention(w)).length+routes.filter(r=>r.status==='ambiguous').length;}
function filteredWorkers(){return DM.filterWorkers(workers,{query:$('searchWorkers').value,filter:$('filterWorkers').value});}
function renderWorkers(){const list=filteredWorkers(),view=DM.pageWorkers(list,page,Number($('workerPageSize').value||25));page=view.page;$('workersBody').replaceChildren(...view.items.map(workerRow));$('emptyWorkers').hidden=view.total!==0;$('workerPager').hidden=view.total<=view.size;$('workerRange').textContent=view.total?`${view.start}–${view.end} / ${view.total}`:'0–0 / 0';$('workerPrev').disabled=view.page===0;$('workerNext').disabled=view.page>=view.pages-1;}
function workerIssue(t){if(DM.hasCooldown(t)){const kind=t.cooldownKind||t.lastError||'cooldown';return`${kind} · until ${formatTime(t.cooldownUntil)}`;}return t.lastError||'—';}
function actionButton(label,action,id){const b=document.createElement('button');b.textContent=label;b.className='soft small';b.dataset.workerAction=action;b.dataset.targetId=id;return b;}
function workerRow(worker){const tr=document.createElement('tr'),state=worker.structure.structuralState,cells=[worker.target.workerLabel||'—',worker.target.title||worker.target.url||'—',state,worker.target.status||'stopped',workerIssue(worker.target),String(worker.target.sentCount||0)];for(const value of cells){const td=document.createElement('td');td.textContent=value;tr.append(td);}const action=document.createElement('td');action.className='row-actions';if(worker.tab?.id)action.append(actionButton('열기','open',worker.target.id));if(worker.target.status==='running')action.append(actionButton('중지','stop',worker.target.id));else if(worker.tab?.id)action.append(actionButton('시작','start',worker.target.id));tr.append(action);return tr;}
async function workerAction(event){const b=event.target.closest('button[data-worker-action]');if(!b)return;const id=b.dataset.targetId,action=b.dataset.workerAction,w=workers.find(x=>x.target.id===id);if(!w)return;b.disabled=true;try{if(action==='open'){if(w.tab?.id)await chrome.tabs.update(w.tab.id,{active:true});return;}const targets=await loadTargets(),i=targets.findIndex(t=>t.id===id);if(i<0)throw new Error('target_missing');const t=targets[i];if(action==='stop'){targets[i]={...t,status:'stopped',stopReason:'dashboard_stop'};await saveTargets(targets);toast(`Worker ${t.workerLabel||''} 중지`);await refresh();return;}if(action==='start'){if(!w.tab?.id)throw new Error('target_tab_not_open');if(!String(t.url||'').trim()||!String(t.prompt||'').trim())throw new Error('target_not_configured');const runId=crypto.randomUUID(),next={...t,status:'running',startedAt:Date.now(),sentCount:0,lastSentAt:null,cooldownStep:0,cooldownAttempt:undefined,cooldownUntil:null,cooldownKind:'',lastError:'',stopReason:'',runId,completedAt:null,completionSeenSignal:'',completionSignalType:'',completionSignalUrl:`${COMPLETE_PREFIX}${encodeURIComponent(runId)}`};targets[i]=next;await saveTargets(targets);if(next.mode==='response'&&next.sendImmediately!==false){const reply=await chrome.tabs.sendMessage(w.tab.id,{type:'PARROT_START',targetId:id,delayMs:Math.max(0,Number(next.delaySec||0))*1000});if(!reply?.ok){targets[i]={...next,status:'stopped',lastError:reply?.reason||'start_not_accepted'};await saveTargets(targets);throw new Error(reply?.reason||'start_not_accepted');}}toast(`Worker ${next.workerLabel||''} 시작`);await refresh();}}catch(e){toast(`처리 실패: ${String(e?.message||e)}`);b.disabled=false;}}
function renderRoutes(){const sorted=[...routes].sort((a,b)=>Number(b.createdAt||b.ambiguousAt||0)-Number(a.createdAt||a.ambiguousAt||0));$('routingBody').replaceChildren(...sorted.slice(0,100).map(routeRow));$('emptyRouting').hidden=sorted.length!==0;}
function routeRow(route){const tr=document.createElement('tr');for(const value of[route.type||'ROUTE',`${route.from||'—'} → ${route.targetRouteId||route.to||'—'}`,route.status||'pending',formatTime(route.deliveredAt||route.resolvedAt||route.ambiguousAt||route.createdAt)]){const td=document.createElement('td');td.textContent=value;tr.append(td);}const action=document.createElement('td');if(route.status==='ambiguous')for(const[label,type]of[['Retry','PARROT_ROUTE_RETRY'],['Resolve','PARROT_ROUTE_RESOLVE']]){const b=document.createElement('button');b.textContent=label;b.className='soft small';b.dataset.queueId=route.queueId;b.dataset.routeAction=type;action.append(b);}tr.append(action);return tr;}
async function routeAction(event){const b=event.target.closest('button[data-route-action]');if(!b)return;b.disabled=true;const result=await chrome.runtime.sendMessage({type:b.dataset.routeAction,queueId:b.dataset.queueId});toast(result?.ok?'처리했습니다.':`처리 실패: ${result?.reason||'unknown'}`);await refresh();}
function renderEvents(events){const list=Array.isArray(events)?events.slice(-50).reverse():[];$('events').replaceChildren(...list.map(event=>{const div=document.createElement('div');div.className='event';div.textContent=`${formatTime(event.at)} ${event.type||'event'} ${event.workerLabel||''}`.trim();return div;}));$('emptyEvents').hidden=list.length!==0;}
function formatTime(value){const n=Number(value);return Number.isFinite(n)&&n>0?new Date(n).toLocaleString():'—';}function toast(message){$('toast').textContent=message;setTimeout(()=>{$('toast').textContent='';},2500);}
